token: 'Mzc5NDAyMDk1OTE0MTIzMjY0.Do8gQQ.K7GAaOCFKorOIBQwhIcedhZav90'

manhole_enable: true
manhole_bind: 127.0.0.1:7171

DSN: 'https://bbd7072c49a640b8b953dd58d8612d0b:2f802e0bfb0c4a4cae915fe6cb911c48@sentry.io/1244425'

web:
  SECRET_KEY: 'A1RPL4NE'
  DISCORD_CLIENT_ID: '351097525928853506'
  DISCORD_REDIRECT_URI: 'http://locahost:8080/api/auth/discord/callback'
  DISCORD_CLIENT_SECRET: '3CrFrIIKEnu_ypsIl5OVoRYM6wlbRm2J'
  DISCORD_API_BASE_URL: 'https://discordapp.com/api'
  DISCORD_TOKEN_URL: 'https://discordapp.com/api/oauth2/token'
  DISCORD_AUTH_URL: 'https://discordapp.com/oauth2/authorize'

state:
  sync_guild_members: true

bot:
  commands_enabled: false
  plugins:
    - rowboat.plugins.core
    - rowboat.plugins.modlog
    - rowboat.plugins.admin
    - rowboat.plugins.spam
    - rowboat.plugins.censor
    - rowboat.plugins.reddit
    - rowboat.plugins.starboard
    - rowboat.plugins.utilities
    - rowboat.plugins.sql
    - rowboat.plugins.internal
    - rowboat.plugins.tags
    - rowboat.plugins.latency
    - rowboat.plugins.infractions
    - rowboat.plugins.memes
    - rowboat.plugins.stats